version: "3.9"

services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - scraper
    networks:
      - parser_net

  scraper:
    build:
      context: ./parser
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - parser_net

networks:
  parser_net:
